# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfstateproxy < Formula
  desc "Terraform state HTTP backend proxy with pluggable storage (1Password, GitHub)"
  homepage "https://github.com/simon0191/tfstateproxy"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/simon0191/tfstateproxy/releases/download/v0.1.0/tfstateproxy_0.1.0_darwin_amd64.tar.gz"
      sha256 "54cfe83329cfe04ff2cd3ae40ccb087d6bc56548ef3e0b66f07ce320c3f7034d"

      define_method(:install) do
        bin.install "tfstateproxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/simon0191/tfstateproxy/releases/download/v0.1.0/tfstateproxy_0.1.0_darwin_arm64.tar.gz"
      sha256 "740e67042b9c835ad8ee796ba519e48f3a48e09e244f4136f62b519c93690f3a"

      define_method(:install) do
        bin.install "tfstateproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/simon0191/tfstateproxy/releases/download/v0.1.0/tfstateproxy_0.1.0_linux_amd64.tar.gz"
      sha256 "66e174bc6918d7de945e6a5ab29af717af4d5424969c83a43cd9e22c59f5ba76"
      define_method(:install) do
        bin.install "tfstateproxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simon0191/tfstateproxy/releases/download/v0.1.0/tfstateproxy_0.1.0_linux_arm64.tar.gz"
      sha256 "e36ba706661c037e9efec64834703d76bb00b006e8131679b5907ecd92774f45"
      define_method(:install) do
        bin.install "tfstateproxy"
      end
    end
  end
end
